name: 'Upload to Blossom (Nostr)'
description: 'Upload a file to Blossom (nostr)'
branding:
  color: purple
  icon: upload
inputs:
  host:
    description: 'The host to upload to'
    required: true
  filePath:
    description: 'The full filePath of the file to upload'
    required: true
outputs:
  blossom-hash:
    description: 'The hash of the file on blossom'
    value: ${{ steps.upload.outputs.blossom-hash }}
runs:
  using: 'node20'
  main: 'dist/index.js'
